### ISSUE TITLE
Does webrtc support H.265 ?

### ISSUE THREAD

**Issue by xieenming** [webrtc-sdk/webrtc#19]
Hello, I would like to know if webrtc supports [H.265](https://en.wikipedia.org/wiki/High_Efficiency_Video_Coding) ?

If not, will you support it recently ?

Thanks a lot!

**Comment by davidliu** [comment]
This library does not natively support H265 at the moment, and I don't know of any upstream plans from google to add the encoder/decoders for it.

A VideoEncoder/DecoderFactory can be passed in to add support for it, but that'll require implementing the codec yourself. There's some information here: https://groups.google.com/g/discuss-webrtc/c/6kokPpnSO3Y

**Comment by xieenming** [comment]
> This library does not natively support H265 at the moment, and I don't know of any upstream plans from google to add the encoder/decoders for it.
> 
> A VideoEncoder/DecoderFactory can be passed in to add support for it, but that'll require implementing the codec yourself. There's some information here: https://groups.google.com/g/discuss-webrtc/c/6kokPpnSO3Y

Thanks a lot.
