### ISSUE TITLE
Problems with SDK

### ISSUE THREAD

**Issue by fjserrano1** [webrtc-sdk/webrtc#32]
Hello!

I have compiled the sdk for android and generated the libwebrtc.aar with your sources.
Now, my problem is this:

e: /Library/Flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.8.7/android/src/main/java/com/cloudwebrtc/webrtc/SimulcastVideoEncoderFactoryWrapper.kt: (182, 9): 'setRates' overrides nothing
e: /Library/Flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.8.7/android/src/main/java/com/cloudwebrtc/webrtc/SimulcastVideoEncoderFactoryWrapper.kt: (182, 58): Unresolved reference: RateControlParameters
e: /Library/Flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.8.7/android/src/main/java/com/cloudwebrtc/webrtc/SimulcastVideoEncoderFactoryWrapper.kt: (183, 35): Not enough information to infer type variable T
e: /Library/Flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.8.7/android/src/main/java/com/cloudwebrtc/webrtc/SimulcastVideoEncoderFactoryWrapper.kt: (183, 42): Not enough information to infer type variable V
e: /Library/Flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.8.7/android/src/main/java/com/cloudwebrtc/webrtc/SimulcastVideoEncoderFactoryWrapper.kt: (183, 77): Unresolved reference: setRates
e: /Library/Flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.8.7/android/src/main/java/com/cloudwebrtc/webrtc/SimulcastVideoEncoderFactoryWrapper.kt: (192, 9): 'getEncoderInfo' overrides nothing
e: /Library/Flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.8.7/android/src/main/java/com/cloudwebrtc/webrtc/SimulcastVideoEncoderFactoryWrapper.kt: (192, 53): Unresolved reference: EncoderInfo
e: /Library/Flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.8.7/android/src/main/java/com/cloudwebrtc/webrtc/SimulcastVideoEncoderFactoryWrapper.kt: (193, 35): Not enough information to infer type variable T
e: /Library/Flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.8.7/android/src/main/java/com/cloudwebrtc/webrtc/SimulcastVideoEncoderFactoryWrapper.kt: (193, 42): Not enough information to infer type variable V
e: /Library/Flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.8.7/android/src/main/java/com/cloudwebrtc/webrtc/SimulcastVideoEncoderFactoryWrapper.kt: (193, 77): Unresolved reference: encoderInfo

any ideas?

Thank you in advance

**Comment by cloudwebrtc** [comment]
I think you need to checkout the m97_release.

**Comment by hiroshihorie** [comment]
I think I will close this for now, please re-open if issue exists in m114 branch.
