### ISSUE TITLE
Need a way to tell to use software decoding instead of setting HW as primary and fallback to SW

### ISSUE THREAD

**Issue by MohamedRisaldarTA** [webrtc-sdk/webrtc#33]

**Comment by MohamedRisaldarTA** [comment]
Similar one here,
#https://github.com/flutter-webrtc/flutter-webrtc/issues/998

**Comment by davidliu** [comment]
What platform is this for? You should already be able to set software decoding directly.

**Comment by MohamedRisaldarTA** [comment]
> What platform is this for? 

This is for Android.

> You should already be able to set software decoding directly.

Is that means we can pass some arguments when building aar library to set it?

**Comment by davidliu** [comment]
When creating a PeerConnectionFactory, a video decoder factory can set in code like so:

```
PeerConnectionFactory.builder()
            .setAudioDeviceModule(audioDeviceModule)
            .setVideoEncoderFactory(videoEncoderFactory)
            .setVideoDecoderFactory(videoDecoderFactory)
            .createPeerConnectionFactory()
```

`SoftwareVideoDecoderFactory` will make it only use software video decoding.

**Comment by Rychou** [comment]
@davidliu Hi, is there a way for Javascript to force sw decoder in Android Chrome?

**Comment by davidliu** [comment]
We don't control the webrtc on chrome, and we're not the originators of webrtc. Can't help you there.
