### ISSUE TITLE
How to build WebRTC-SDK xcframework

### ISSUE THREAD

**Issue by pannawatth** [webrtc-sdk/webrtc#43]
I am looking for a way to build WebRTC-SDK xcframework (for ios) from my forked webrtc git after editing some code.
I tried to follow the process from the git below.
https://github.com/alexpiezo/WebRTC

But it appear that the generated framework file doesn't contain some header files present in the original code.
Does anyone know what I might have done wrong?

thank you

**Comment by nikohpng** [comment]
same issue

**Comment by nikohpng** [comment]
I find build script [webrtc-build](https://github.com/webrtc-sdk/webrtc-build)

**Comment by JiaoLiu** [comment]
can you susscess build the xframework?

the generated framework file doesn't contain some header files
[RTCAudioDeviceModule.h、RTCYUVHelper.h xxxxxxxx]


> I find build script [webrtc-build](https://github.com/webrtc-sdk/webrtc-build)

**Comment by nikohpng** [comment]
I have successed, you have see [this](https://github.com/webrtc-sdk/webrtc-build/blob/main/docs/build.md)

**Comment by JiaoLiu** [comment]
@hiroshihorie @davidzhao @nikohpng The webrtc_build script generated macOS framework is not functioning, but the iOS framework is working fine.

latest branch (https://github.com/webrtc-sdk/webrtc) generated macOS framework displays the following error:
![5601700206806_ pic](https://github.com/webrtc-sdk/webrtc/assets/4370982/56d55fc2-ba74-4da3-ad49-09d5d7b3d11b)
