### ISSUE TITLE
How we are planning to include the fixes made to m104_release into m114_release

### ISSUE THREAD

**Issue by MohamedRisaldarTA** [webrtc-sdk/webrtc#82]
I can see lot of commits to fix / overcome issues are available on branch m104_release but not on m114_release.
I would like to know about how we are planning to include them.

**Comment by cloudwebrtc** [comment]
We have actually merged m104 and all previous patches into m114 through 8 big patches. Let me know if I missed anything
https://github.com/webrtc-sdk/webrtc/pull/76

**Comment by MohamedRisaldarTA** [comment]
Ok.
I see that all the changes are included in the patches but we missed #78.

**Comment by cloudwebrtc** [comment]
Ah, sorry, I forgot this PR,  okay, let me cherry-pick to m114 first, the next upgrade to the m version will be merged into `Android improvements`

**Comment by MohamedRisaldarTA** [comment]
> Ah, sorry, I forgot this PR, okay, let me cherry-pick to m114 first, the next upgrade to the m version will be merged into `Android improvements`

Okay, Thanks.

**Comment by cloudwebrtc** [comment]
Ok, just merged into https://github.com/webrtc-sdk/webrtc/commit/61fc7d615ac87d67762a94b4c700aa4c33f79a84

**Comment by MohamedRisaldarTA** [comment]
Thanks.
